name: C/C++ CI

on:
  push:
    branches: [ main, cmake ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev libdirectfb-dev libgtest-dev libsqlite3-dev
    - uses: actions/checkout@v4
      with:
          submodules: true
          fetch-depth: 0
    - uses: lukka/get-cmake@latest
    - uses: lukka/run-vcpkg@v11
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'default'
        buildPreset: 'default'
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.7
      with:
        run: |
          cp build/tests ./tests
          ./tests
  Windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'avara-exe'
          buildPreset: 'avara-exe'
      - name: Run headless test
        run: |
          cp build\tests.exe .\tests.exe 
          .\tests.exe
        shell: pwsh
      - name: WinAvara Zip
        run: bin\winavarazip.ps1
      - name: deploy main nightly
        if: startsWith(github.repository_owner, 'avaraline') && endsWith(github.ref, 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./WinAvara.zip
          asset_name: Avara-Windows-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1
  macOS:
    name: macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'avara-app'
          buildPreset: 'avara-app'
      - name: run tests
        run: cp build/tests ./tests; ./tests
      - name: make macdist
        run: zip -rq MacAvara.zip ./build/Avara.app
      - name: deploy main nightly
        if: startsWith(github.repository_owner, 'avaraline') && endsWith(github.ref, 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./MacAvara.zip
          asset_name: Avara-macOS-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1
