name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
      - name: install dependencies
        run: |
          wget -q "https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-2.26.2.dmg"
          hdiutil attach SDL2-2.26.2.dmg
          sudo cp -R /Volumes/SDL2/SDL2.framework /Library/Frameworks/
          brew install googletest
      - uses: actions/checkout@v4
      - name: Run headless tests
        run: make -j3 tests
      - name: make macdist
        run: make -j3 clean macdist
      - name: deploy main nightly
        if: startsWith(github.repository_owner, 'avaraline') && endsWith(github.ref, 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./build/MacAvara.zip
          asset_name: Avara-macOS-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1
