name: Beta Release

on: workflow_dispatch

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'avara-exe'
          buildPreset: 'avara-exe'
      - name: Deploy beta
        if: startsWith(github.repository_owner, 'avaraline') && (github.refname != 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./WinAvara.zip
          asset_name: Avara-Windows-BETA-$$.zip
          asset_content_type: application/zip
          max_releases: 1
  macOS:
    name: MacOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'avara-app'
          buildPreset: 'avara-app'
      - name: make macdist
        run: zip -rq MacAvara.zip ./build/Avara.app
      - name: Deploy beta
        if: startsWith(github.repository_owner, 'avaraline') && (github.ref != 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./MacAvara.zip
          asset_name: Avara-MacOS-BETA-$$.zip
          asset_content_type: application/zip
          max_releases: 1
