name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev libsdl2-net-dev libdirectfb-dev
    - uses: actions/checkout@v2
    - name: make
      run: make -j
    - name: make tests
      run: make tests
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: ./build/tests
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: zip git mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_net mingw-w64-x86_64-clang mingw-w64-x86_64-glbinding mingw-w64-x86_64-glew make
      - uses: actions/checkout@v2
      - name: make
        shell: msys2 {0}
        run: |
          make -j winapp
          make tests
          build/tests
      - name: deploy nightly
        if: ${{startsWith(env.GITHUB_REPOSITORY, 'avaraline')}}
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./build/WinAvara.zip
          asset_name: Avara-Windows-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1

  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
      - name: install dependencies
        run: |
          wget -q "https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.dmg"
          hdiutil attach SDL2_net-2.0.1.dmg
          sudo cp -R /Volumes/SDL2_net/SDL2_net.framework /Library/Frameworks/
          wget -q "http://libsdl.org/release/SDL2-2.0.12.dmg"
          hdiutil attach SDL2-2.0.12.dmg
          sudo cp -R /Volumes/SDL2/SDL2.framework /Library/Frameworks/
      - uses: actions/checkout@v2
      - name: make
        run: make -j macapp SIGNING_ID=NONE
      - name: make tests
        run: make tests
      - name: run tests
        run: build/tests
      - name: deploy nightly
        if: ${{startsWith(env.GITHUB_REPOSITORY, 'avaraline')}}
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./build/MacAvara.zip
          asset_name: Avara-macOS-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1
