name: C/C++ CI

on:
  push:
    branches: [ main, cmake ]
  pull_request:
    branches: [ main ]

jobs:
  Windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Vcpkg Integration
        run: |
          $vcpkg_path = (Join-Path ${env:VCPKG_INSTALLATION_ROOT} vcpkg.exe)
          &$vcpkg_path integrate install
        shell: pwsh
      - name: Build
        run: |
          New-Item -Path .\out -ItemType Directory
          Set-Location -Path .\out
          $vcpkg_cmake = "-DCMAKE_TOOLCHAIN_FILE=" + (Join-Path ${env:VCPKG_INSTALLATION_ROOT} scripts\buildsystems\vcpkg.cmake)
          cmake .. $vcpkg_cmake
          cmake --build . --target package --config release
        shell: pwsh
      - name: deploy main nightly
        if: startsWith(github.repository_owner, 'avaraline') && endsWith(github.ref, 'cmake')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./out/Avara-0.7.1-win64.exe
          asset_name: Avara-Windows-Nightly-$$-installer.exe
          asset_content_type: application/vnd.microsoft.portable-executable
          max_releases: 1
