name: C/C++ CI

on:
  push:
    branches: [ cmake, main, fps-hybrid ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev libdirectfb-dev libminiupnpc-dev
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        make -j
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: make tests
  Windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Vcpkg Integration
        run: |
          $vcpkg_path = (Join-Path ${env:VCPKG_INSTALLATION_ROOT} vcpkg.exe)
          &$vcpkg_path integrate install
        shell: pwsh
      - name: Build
        run: msbuild /m /p:Platform=x64 /p:Configuration=Release ./Avara.sln
        shell: pwsh
      - name: Archive
        run: Compress-Archive -Path ./out/build/x64-Release -DestinationPath WinAvara.zip
        shell: pwsh
      - name: deploy main nightly
        if: startsWith(github.repository_owner, 'avaraline') && endsWith(github.ref, 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./WinAvara.zip
          asset_name: Avara-Windows-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: install dependencies
        run: |
          wget -q "https://www.libsdl.org/release/SDL2-2.0.14.dmg"
          hdiutil attach SDL2-2.0.14.dmg
          sudo cp -R /Volumes/SDL2/SDL2.framework /Library/Frameworks/
      - uses: actions/checkout@v2
      - name: make
        run: |
          mkdir build && cd build
          cmake ..
          make -j
      - name: tests
        run: ./tests
      - name: print env variables
        run: echo $GITHUB_REPOSITORY && echo $GITHUB_REF
      - name: deploy main nightly
        if: startsWith(github.repository_owner, 'avaraline') && endsWith(github.ref, 'main')
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/avaraline/Avara/releases/28954246/assets{?name,label}
          release_id: 28954246
          asset_path: ./build/MacAvara.zip
          asset_name: Avara-macOS-Nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 1
